language: c
sudo: enabled
dist: trusty

notifications:
  email: true

before_install:
  - sudo apt-get install build-essential cmake iverilog tk binutils-msp430 gcc-msp430 msp430-libc msp430mcu expect-dev verilator -y

install:
  - mkdir build && cd build && cmake .. && cd ..

script:
  - cd core/sim/rtl_sim/run/
  - ./$TARGET

env:
  - TARGET=run_all
  - TARGET=run_all_sancus
